install: 
  - sudo apt-get install qt4-dev-tools
  - bundle install
script: bundle exec rspec
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
notifications:
  email:
    - boris@roundlake.ru
    - p.zotov@roundlake.ru
