language: ruby
install:
  - "sudo apt-get install qt4-dev-tools --no-install-recommends"
  - "gem update --system"
  - "(cd ext/; ruby extconf.rb; make)"
  - "bundle install"
script:
  - "xvfb-run bundle exec rspec"
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx-19mode
env:
  - EXPERIMENTAL=false
  - EXPERIMENTAL=true
matrix:
  exclude:
    - rvm: 1.9.2
    - rvm: 1.9.3
  allow_failures:
    - env: EXPERIMENTAL=true