language: ruby
install:
  - "sudo apt-get install qt4-dev-tools --no-install-recommends"
  - "(cd ext/; ruby extconf.rb; make)"
  - "bundle install"
script:
  - "xvfb-run bundle exec rspec"
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx-19mode
env:
  - EXPERIMENTAL=true
  - EXPERIMENTAL=false
matrix:
  exclude:
    - rvm: 1.9.2
      env: EXPERIMENTAL=true
    - rvm: 1.9.3
      env: EXPERIMENTAL=true
  allow_fail:
    - env: EXPERIMENTAL=true
notifications:
  email:
    - boris@roundlake.ru
    - p.zotov@roundlake.ru
