install: 
  - "sudo apt-get install qt4-dev-tools"
  - "cd ext/; ruby extconf.rb; make; cd ../;"
  - "bundle install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "bundle exec rspec"
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
notifications:
  email:
    - boris@roundlake.ru
    - p.zotov@roundlake.ru
